#ifndef TRIVIAL_CORE_TIME_TIME_CONFIG_H
#define TRIVIAL_CORE_TIME_TIME_CONFIG_H

#include <trivial/core/config.h>

#define TRIVIAL_TIME_NANOSECONDS_PER_SECOND 1'000'000'000
#define TRIVIAL_TIME_NANOSECONDS_PER_MILLISECOND 1'000'000
#define TRIVIAL_TIME_NANOSECONDS_PER_MICROSECOND 1'000

#define TRIVIAL_TIME_MILLISECOND_ROUNDING_NS (TRIVIAL_TIME_NANOSECONDS_PER_MILLISECOND - 1)

#endif // TRIVIAL_CORE_TIME_TIME_CONFIG_H
