#ifndef TRIVIAL_CORE_TIME_TIME_CONSTANTS_H
#define TRIVIAL_CORE_TIME_TIME_CONSTANTS_H

#define TRIVIAL_TIME_NANOSECONDS_PER_SECOND 1'000'000'000 // NOLINT(cppcoreguidelines-macro-usage)
#define TRIVIAL_TIME_NANOSECONDS_PER_MILLISECOND 1'000'000 // NOLINT(cppcoreguidelines-macro-usage)
#define TRIVIAL_TIME_NANOSECONDS_PER_MICROSECOND 1'000 // NOLINT(cppcoreguidelines-macro-usage)

#define TRIVIAL_TIME_MILLISECOND_ROUNDING_NS (TRIVIAL_TIME_NANOSECONDS_PER_MILLISECOND - 1) // NOLINT(cppcoreguidelines-macro-usage)

#endif // TRIVIAL_CORE_TIME_TIME_CONSTANTS_H
