#ifndef TRIVIAL_PLATFORM_PLATFORM_CONFIG_H
#define TRIVIAL_PLATFORM_PLATFORM_CONFIG_H

#include <trivial/core/config.h>

#ifndef TRIVIAL_PLATFORM_DEFAULT_WINDOW_WIDTH
#define TRIVIAL_PLATFORM_DEFAULT_WINDOW_WIDTH 1280
#endif

#ifndef TRIVIAL_PLATFORM_DEFAULT_WINDOW_HEIGHT
#define TRIVIAL_PLATFORM_DEFAULT_WINDOW_HEIGHT 720
#endif

#ifndef TRIVIAL_PLATFORM_DEFAULT_WINDOW_TITLE
#define TRIVIAL_PLATFORM_DEFAULT_WINDOW_TITLE "Trivial"
#endif

static_assert(TRIVIAL_PLATFORM_DEFAULT_WINDOW_WIDTH > 0 && TRIVIAL_PLATFORM_DEFAULT_WINDOW_HEIGHT > 0,
              "Default window dimensions must be non-zero");

static_assert(sizeof(TRIVIAL_PLATFORM_DEFAULT_WINDOW_TITLE) > 1, "Default window title must be non-empty");

#endif // TRIVIAL_PLATFORM_PLATFORM_CONFIG_H
