#ifndef TRIVIAL_CORE_CONFIG_H
#define TRIVIAL_CORE_CONFIG_H

#ifndef TRIVIAL_ENABLE_ASSERTS
#define TRIVIAL_ENABLE_ASSERTS 1
#endif

#ifndef TRIVIAL_ENABLE_SLOW_ASSERTS
#define TRIVIAL_ENABLE_SLOW_ASSERTS 0
#endif

#ifndef TRIVIAL_ENABLE_LOGGING
#define TRIVIAL_ENABLE_LOGGING 1
#endif

#ifndef TRIVIAL_ENABLE_VULKAN_VALIDATION
#define TRIVIAL_ENABLE_VULKAN_VALIDATION 1
#endif

#ifndef TRIVIAL_ENABLE_TRACY
#define TRIVIAL_ENABLE_TRACY 0
#endif

#ifndef TRIVIAL_CONFIG_DEBUG
#define TRIVIAL_CONFIG_DEBUG 0
#endif

#ifndef TRIVIAL_CONFIG_RELEASE
#define TRIVIAL_CONFIG_RELEASE 0
#endif

#ifndef TRIVIAL_CONFIG_RELWITHDEBINFO
#define TRIVIAL_CONFIG_RELWITHDEBINFO 0
#endif

#endif // TRIVIAL_CORE_CONFIG_H
